const actions = {
  LOADING_PRODUCTS: "LOADING_PRODUCTS",
  LOADING_CATEGORIES: "LOADING_CATEGORIES",
  FETCH_ERROR: "FETCH_ERROR",
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  FETCH_CATEGORIES: "FETCH_CATEGORIES",
  SET_FILTERED_PRODUCTS: "SET_FILTERED_PRODUCTS",
  FILTER_BY_CATEGORY: "FILTER_BY_CATEGORY",
  FILTER_BY_PRICE: "FILTER_BY_PRICE",
  FILTER_BY_COLOR: "FILTER_BY_COLOR",
  SEARCH_PRODUCT: "SEARCH_PRODUCT",
  CHANGE_TITLE: "CHANGE_TITLE",
};
export default actions;
